/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visual;

import Logica.Concepto;
import Logica.Tecnologia;
import Logica.TipoTecnologia;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Facu
 */
public class AltaProyectoInter extends javax.swing.JInternalFrame {

    private ControladoraVisual miControladoraVisual;
    private DefaultTableModel modeloProyecto;
    public static DefaultTableModel modeloConceptoProyec;
    public static DefaultTableModel modeloTecnologiaProyec;
    private Concepto unConcepto;
    private Tecnologia unaTecnologia;
    private int filaConcepto;
    private int filaTecnologia;

    /**
     * Creates new form AltaProyectoInter
     */
    public AltaProyectoInter(ControladoraVisual miControladoraVisual) {
        initComponents();
        this.miControladoraVisual = miControladoraVisual;
        this.modeloConceptoProyec = (DefaultTableModel) this.tblConceptoProyec.getModel();
        this.modeloTecnologiaProyec = (DefaultTableModel) this.tblTecnologiaProyec.getModel();
        this.cmdBorrarConcepto.setEnabled(false);
        this.cmdBorrarTecnologia.setEnabled(false);
        refrescarVentana();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTiempoEstimado = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblConceptoProyec = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblTecnologiaProyec = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        cmdAgregarConcepto = new javax.swing.JButton();
        cmdBorrarConcepto = new javax.swing.JButton();
        cmdAgregarTecnologia = new javax.swing.JButton();
        cmdBorrarTecnologia = new javax.swing.JButton();
        cmdGenerarProyecto = new javax.swing.JButton();
        cmdVerProyecto = new javax.swing.JButton();

        setClosable(true);
        setTitle("Proyectos");

        txtTiempoEstimado.setText("En Horas de Desarrollo");
        txtTiempoEstimado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTiempoEstimadoActionPerformed(evt);
            }
        });

        jLabel1.setText("Descripcion:");

        jLabel2.setText("Tiempo Estimado:");

        tblConceptoProyec.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Codigo", "Descripcion", "Monto"
            }
        ));
        tblConceptoProyec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblConceptoProyecMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblConceptoProyec);

        tblTecnologiaProyec.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Codigo", "Descripcion", "Tipo de Tecnologia"
            }
        ));
        tblTecnologiaProyec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTecnologiaProyecMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblTecnologiaProyec);

        jLabel6.setText("Tecnologias:");

        jLabel7.setText("Conceptos:");

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        jScrollPane1.setViewportView(txtDescripcion);

        cmdAgregarConcepto.setText("Agregar Concepto");
        cmdAgregarConcepto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAgregarConceptoActionPerformed(evt);
            }
        });

        cmdBorrarConcepto.setText("Borrar Concepto");
        cmdBorrarConcepto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBorrarConceptoActionPerformed(evt);
            }
        });

        cmdAgregarTecnologia.setText("Agregar Tecnologia");
        cmdAgregarTecnologia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAgregarTecnologiaActionPerformed(evt);
            }
        });

        cmdBorrarTecnologia.setText("Borrar Tecnologia");
        cmdBorrarTecnologia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBorrarTecnologiaActionPerformed(evt);
            }
        });

        cmdGenerarProyecto.setText("Generar Proyecto");
        cmdGenerarProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdGenerarProyectoActionPerformed(evt);
            }
        });

        cmdVerProyecto.setText("Ver Proyectos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmdBorrarTecnologia, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmdAgregarTecnologia, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(26, 26, 26))
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtTiempoEstimado, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jScrollPane1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmdVerProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmdGenerarProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmdBorrarConcepto, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(334, 334, 334)
                                .addComponent(cmdAgregarConcepto, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTiempoEstimado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(96, 96, 96)
                        .addComponent(jLabel7))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdBorrarConcepto)
                    .addComponent(cmdAgregarConcepto))
                .addGap(20, 20, 20)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdBorrarTecnologia)
                    .addComponent(cmdAgregarTecnologia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdGenerarProyecto)
                    .addComponent(cmdVerProyecto))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdBorrarConceptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBorrarConceptoActionPerformed
        AltaProyectoInter.modeloConceptoProyec.removeRow(filaConcepto);
        this.cmdBorrarConcepto.setEnabled(false);
    }//GEN-LAST:event_cmdBorrarConceptoActionPerformed

    private void txtTiempoEstimadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTiempoEstimadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTiempoEstimadoActionPerformed

    private void cmdAgregarConceptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAgregarConceptoActionPerformed
        ListarConceptoInter unConcepto = new ListarConceptoInter(miControladoraVisual);
        MenuPrincipal.Escritorio.add(unConcepto);
        unConcepto.show();
    }//GEN-LAST:event_cmdAgregarConceptoActionPerformed

    private void cmdAgregarTecnologiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAgregarTecnologiaActionPerformed
        ListarTecnologiaInter unListarTecnologiaInter = new ListarTecnologiaInter(miControladoraVisual);
        MenuPrincipal.Escritorio.add(unListarTecnologiaInter);
        unListarTecnologiaInter.show();
    }//GEN-LAST:event_cmdAgregarTecnologiaActionPerformed

    private void tblConceptoProyecMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblConceptoProyecMouseClicked
        this.filaConcepto = this.tblConceptoProyec.rowAtPoint(evt.getPoint());
        this.cmdBorrarConcepto.setEnabled(true);
    }//GEN-LAST:event_tblConceptoProyecMouseClicked

    private void tblTecnologiaProyecMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTecnologiaProyecMouseClicked
        this.filaTecnologia = this.tblTecnologiaProyec.rowAtPoint(evt.getPoint());
        this.cmdBorrarTecnologia.setEnabled(true);
    }//GEN-LAST:event_tblTecnologiaProyecMouseClicked

    private void cmdBorrarTecnologiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBorrarTecnologiaActionPerformed
        AltaProyectoInter.modeloTecnologiaProyec.removeRow(filaTecnologia);
        this.cmdBorrarTecnologia.setEnabled(false);
    }//GEN-LAST:event_cmdBorrarTecnologiaActionPerformed

    private void cmdGenerarProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdGenerarProyectoActionPerformed
        List<Concepto> unosConceptos = new LinkedList<>();
        List<Tecnologia> unasTecnologias = new LinkedList<>();
        Concepto unConcepto;
        Tecnologia unaTecnologia;
        int codigo;
        for (int i = 0; i < AltaProyectoInter.modeloConceptoProyec.getRowCount(); i++) {
            codigo = Integer.parseInt(AltaProyectoInter.modeloConceptoProyec.getValueAt(i, 0).toString());
            unConcepto = this.miControladoraVisual.buscarConcepto(codigo);
            unosConceptos.add(unConcepto);
        }
        for (int i = 0; i < AltaProyectoInter.modeloTecnologiaProyec.getRowCount(); i++) {
            codigo = Integer.parseInt(AltaProyectoInter.modeloConceptoProyec.getValueAt(i, 0).toString());
            unaTecnologia = this.miControladoraVisual.buscarTecnologia(codigo);
            unasTecnologias.add(unaTecnologia);
        }
        try {
            this.miControladoraVisual.generarProyecto(Float.valueOf(this.txtTiempoEstimado.getText()),unosConceptos, unasTecnologias, this.txtDescripcion.getText());
            refrescarVentana();
        } catch (Exception ex) {
            Logger.getLogger(AltaProyectoInter.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmdGenerarProyectoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdAgregarConcepto;
    private javax.swing.JButton cmdAgregarTecnologia;
    private javax.swing.JButton cmdBorrarConcepto;
    private javax.swing.JButton cmdBorrarTecnologia;
    private javax.swing.JButton cmdGenerarProyecto;
    private javax.swing.JButton cmdVerProyecto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tblConceptoProyec;
    private javax.swing.JTable tblTecnologiaProyec;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtTiempoEstimado;
    // End of variables declaration//GEN-END:variables

    private void refrescarVentana() {
        txtDescripcion.setText(null);
        txtTiempoEstimado.setText(null);
        modeloConceptoProyec.setRowCount(0);
        modeloTecnologiaProyec.setRowCount(0);
    }

}
