/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visual;

import Logica.TipoComprobante;
import Logica.TipoVenta;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Facu
 */
public class AltaTipoVentaInter extends javax.swing.JInternalFrame {

    private ControladoraVisual miControladoraVisual;
    private DefaultTableModel modeloTipoVenta;

    public AltaTipoVentaInter(ControladoraVisual miControladoraVisual) {
        initComponents();
        this.txtCodigo.setVisible(false);
        this.miControladoraVisual = miControladoraVisual;
        this.modeloTipoVenta = (DefaultTableModel) this.tblVentas.getModel();
        refrescarVentana();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        txtDescripcion = new javax.swing.JTextField();
        cmdAgregar2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cmdModificar2 = new javax.swing.JButton();
        cmdBorrar2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblVentas = new javax.swing.JTable();
        txtCodigo = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Tipo de Venta");

        cmdAgregar2.setText("Agregar");
        cmdAgregar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAgregar2ActionPerformed(evt);
            }
        });

        jLabel5.setText("Descripcion:");

        cmdModificar2.setText("Modificar");
        cmdModificar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdModificar2ActionPerformed(evt);
            }
        });

        cmdBorrar2.setText("Borrar");
        cmdBorrar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBorrar2ActionPerformed(evt);
            }
        });

        tblVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Codigo", "Descripcion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblVentasMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblVentas);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(cmdAgregar2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmdModificar2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdBorrar2))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCodigo)
                            .addComponent(txtDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(61, 61, 61)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmdModificar2)
                            .addComponent(cmdBorrar2)
                            .addComponent(cmdAgregar2))))
                .addContainerGap(127, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdAgregar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAgregar2ActionPerformed
        try {
            TipoComprobante unTipoVenta = this.miControladoraVisual.buscarTipoComprobante(this.txtDescripcion.getText());
            if (unTipoVenta == null) {
                this.miControladoraVisual.crearTipoVenta(txtDescripcion.getText());
                refrescarVentana();
            } else {
                Object msj = "Ya Existe";
                JOptionPane.showMessageDialog(null, msj, "ERROR: Existencia", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            Logger.getLogger(AltaTipoVentaInter.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmdAgregar2ActionPerformed

    private void cmdModificar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdModificar2ActionPerformed
        try {
            this.miControladoraVisual.modificarTipooVenta(Integer.parseInt(txtCodigo.getText()), txtDescripcion.getText());
            refrescarVentana();
        } catch (Exception ex) {
            Logger.getLogger(AltaTipoVentaInter.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmdModificar2ActionPerformed

    private void cmdBorrar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBorrar2ActionPerformed
        try {
            this.miControladoraVisual.borrarTipoVenta(Integer.parseInt(txtCodigo.getText()));
            refrescarVentana();
        } catch (Exception ex) {
            Logger.getLogger(AltaTipoVentaInter.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmdBorrar2ActionPerformed

    private void tblVentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVentasMouseClicked
        txtCodigo.setText(null);
        txtDescripcion.setText(null);

        int fila = this.tblVentas.rowAtPoint(evt.getPoint());

        txtCodigo.setText(this.modeloTipoVenta.getValueAt(fila, 0).toString());
        txtDescripcion.setText(this.modeloTipoVenta.getValueAt(fila, 1).toString());
    }//GEN-LAST:event_tblVentasMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdAgregar2;
    private javax.swing.JButton cmdBorrar2;
    private javax.swing.JButton cmdModificar2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblVentas;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDescripcion;
    // End of variables declaration//GEN-END:variables

    private void refrescarVentana() {
        txtCodigo.setText(null);
        txtDescripcion.setText(null);
        modeloTipoVenta.setRowCount(0);
        cargarTablaVentas();
    }

    private void cargarTablaVentas() {
        Iterator<TipoVenta> itTipoVenta = this.miControladoraVisual.traerTipoVenta().iterator();
        TipoVenta unTipo;
        while (itTipoVenta.hasNext()) {
            unTipo = itTipoVenta.next();
            modeloTipoVenta.addRow(new Object[]{unTipo.getCodigo(), unTipo.getDescripcion()});
        }
    }
}
