/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visual;

import Logica.Tecnologia;
import Logica.TipoTecnologia;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author eras
 */
public class AltaTecnologiaInter extends javax.swing.JInternalFrame {

    private ControladoraVisual miControladoraVisual;
    private DefaultTableModel modeloTecnologias;

    /**
     * Creates new form AltaTecnologia
     */
    public AltaTecnologiaInter(ControladoraVisual miControladoraVisual) {
        initComponents();
        this.txtCodigo.setVisible(false);
        this.miControladoraVisual = miControladoraVisual;
        this.modeloTecnologias = (DefaultTableModel) this.tblTecnologia.getModel();
        refrescarVentana();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtDescripcion = new javax.swing.JTextField();
        cmdAgregar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cmdModificar = new javax.swing.JButton();
        cmdBorrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTecnologia = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        CmbTipoTecnologia = new javax.swing.JComboBox<>();
        txtCodigo = new javax.swing.JTextField();

        setClosable(true);
        setResizable(true);
        setTitle("Tecnologia");

        cmdAgregar.setText("Agregar");
        cmdAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAgregarActionPerformed(evt);
            }
        });

        jLabel1.setText("Descripcion:");

        cmdModificar.setText("Modificar");
        cmdModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdModificarActionPerformed(evt);
            }
        });

        cmdBorrar.setText("Borrar");
        cmdBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBorrarActionPerformed(evt);
            }
        });

        tblTecnologia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Codigo", "Descripcion", "Tipo de Tecnologia"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblTecnologia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTecnologiaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTecnologia);

        jLabel2.setText("Tipo de Tecnologia:");

        CmbTipoTecnologia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CmbTipoTecnologia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmbTipoTecnologiaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                            .addComponent(CmbTipoTecnologia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(cmdAgregar)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(cmdModificar)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(cmdBorrar)
                    .addContainerGap(643, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(CmbTipoTecnologia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 176, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(139, 139, 139)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmdModificar)
                        .addComponent(cmdBorrar)
                        .addComponent(cmdAgregar))
                    .addContainerGap(138, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAgregarActionPerformed
        try {
           
            String string = (String) this.CmbTipoTecnologia.getSelectedItem();
            String[] parts = string.split("-");
            int codigoTipo = Integer.parseInt(parts[0]);
            TipoTecnologia unTipoTecnologia = this.miControladoraVisual.buscarTipoTecnologia(codigoTipo);
//            TipoTecnologia unTipoTecnologia = (TipoTecnologia) this.CmbTipoTecnologia.getSelectedItem();
            this.miControladoraVisual.crearTecnologia(this.txtDescripcion.getText(), unTipoTecnologia);
            refrescarVentana();
        } catch (Exception ex) {
            Logger.getLogger(AltaTecnologiaInter.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmdAgregarActionPerformed

    private void CmbTipoTecnologiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmbTipoTecnologiaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_CmbTipoTecnologiaActionPerformed

    private void tblTecnologiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTecnologiaMouseClicked
       txtCodigo.setText(null);
       txtDescripcion.setText(null);
       
       int fila = this.tblTecnologia.rowAtPoint(evt.getPoint());
       
       txtCodigo.setText(this.modeloTecnologias.getValueAt(fila, 0).toString());
       txtDescripcion.setText(this.modeloTecnologias.getValueAt(fila, 1).toString());
       CmbTipoTecnologia.setSelectedItem(this.modeloTecnologias.getValueAt(fila, 2).toString());
    }//GEN-LAST:event_tblTecnologiaMouseClicked

    private void cmdModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdModificarActionPerformed
        try {
            String string = (String) this.CmbTipoTecnologia.getSelectedItem();
            String[] parts = string.split("-");
            int codigoTipo = Integer.parseInt(parts[0]);
            TipoTecnologia unTipoTecnologia = this.miControladoraVisual.buscarTipoTecnologia(codigoTipo);
            this.miControladoraVisual.modificarTecnologia(Integer.parseInt(txtCodigo.getText()), txtDescripcion.getText(),unTipoTecnologia);
            refrescarVentana();
        } catch (Exception ex) {
            Logger.getLogger(AltaTecnologiaInter.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmdModificarActionPerformed

    private void cmdBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBorrarActionPerformed
        try {
            this.miControladoraVisual.borrarTecnologia(Integer.parseInt(txtCodigo.getText()));
            refrescarVentana();
        } catch (Exception ex) {
            Logger.getLogger(AltaTecnologiaInter.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmdBorrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CmbTipoTecnologia;
    private javax.swing.JButton cmdAgregar;
    private javax.swing.JButton cmdBorrar;
    private javax.swing.JButton cmdModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTecnologia;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDescripcion;
    // End of variables declaration//GEN-END:variables

    private void refrescarVentana() {
        this.txtCodigo.setText(null);
        this.txtDescripcion.setText(null);
        this.modeloTecnologias.setRowCount(0);
        this.CmbTipoTecnologia.removeAllItems();
        this.cargarTablaTecnologias();
        this.cargarCombo();

    }

    private void cargarTablaTecnologias() {
        Iterator<Tecnologia> itTecnologia = this.miControladoraVisual.traerTecnologias().iterator();
        Tecnologia unaTecnologia;
        while (itTecnologia.hasNext()) {
            unaTecnologia = itTecnologia.next();
            modeloTecnologias.addRow(new Object[]{unaTecnologia.getCodigo(), unaTecnologia.getDescripcion(), unaTecnologia.getUnTipoTecnologia().toString()});
        }
    }

    private void cargarCombo() {
        Iterator<TipoTecnologia> itTiposDeTecnologias = this.miControladoraVisual.traerTiposDeTecnologias().iterator();
        TipoTecnologia unTipo;
        while (itTiposDeTecnologias.hasNext()) {
            unTipo = itTiposDeTecnologias.next();
            this.CmbTipoTecnologia.addItem(unTipo.toString());
        }
    }

}
