/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visual;

/**
 *
 * @author pepex3
 */
public class BalanceGeneralInter extends javax.swing.JInternalFrame {

    private ControladoraVisual miControladoraVisual;
    /**
     * Creates new form BalanceGeneralInter
     */
    public BalanceGeneralInter(ControladoraVisual miControladoraVisual) {
        initComponents();
        this.miControladoraVisual=miControladoraVisual;
        this.lblCantidadVentas.setText(String.valueOf(this.miControladoraVisual.CalcularTotalVentas()));
        this.lblTotalVentas.setText(String.valueOf(this.miControladoraVisual.CalcularTotalVentasArticulos()));
        this.lblCantidadCompras.setText(String.valueOf(this.miControladoraVisual.CalcularTotalCompras()));
        this.lblTotalCompras.setText(String.valueOf(this.miControladoraVisual.calcularTotalCompras()));
        this.lblBalance.setText(String.valueOf(this.miControladoraVisual.calcularBalance()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblCantidadVentas = new javax.swing.JLabel();
        lblTotalVentas = new javax.swing.JLabel();
        lblCantidadCompras = new javax.swing.JLabel();
        lblTotalCompras = new javax.swing.JLabel();
        lblBalance = new javax.swing.JLabel();

        setClosable(true);
        setResizable(true);
        setTitle("Balance General");

        jLabel1.setText("Cantidad de Ventas");

        jLabel2.setText("Total Ventas:");

        jLabel3.setText("Cantidad de Compras:");

        jLabel4.setText("Total Compras:");

        jLabel5.setText("Total:");

        lblCantidadVentas.setText("xxxxxx");

        lblTotalVentas.setText("0.00");

        lblCantidadCompras.setText("xxxxxx");

        lblTotalCompras.setText("0.00");

        lblBalance.setText("0.00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(93, 93, 93)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBalance)
                    .addComponent(lblTotalCompras)
                    .addComponent(lblCantidadCompras)
                    .addComponent(lblTotalVentas)
                    .addComponent(lblCantidadVentas))
                .addContainerGap(163, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblCantidadVentas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblTotalVentas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblCantidadCompras))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblTotalCompras))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblBalance))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblBalance;
    private javax.swing.JLabel lblCantidadCompras;
    private javax.swing.JLabel lblCantidadVentas;
    private javax.swing.JLabel lblTotalCompras;
    private javax.swing.JLabel lblTotalVentas;
    // End of variables declaration//GEN-END:variables
}
