/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visual;

import Logica.Proveedor;
import java.util.Iterator;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pepex3
 */
public class BusquedaProveedorInter extends javax.swing.JInternalFrame {

    private ControladoraVisual miControladoraVisual;
    private DefaultTableModel modeloProveedor;

    /**
     * Creates new form BusquedaProveedorInter
     */
    public BusquedaProveedorInter(ControladoraVisual miControladoraVisual) {
        initComponents();
        this.miControladoraVisual = miControladoraVisual;
        this.modeloProveedor = (DefaultTableModel) this.tblProveedor.getModel();
        refrescarVentana();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblProveedor = new javax.swing.JTable();

        setClosable(true);
        setResizable(true);
        setTitle("Proveedores");

        tblProveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Cuit", "Nombre", "Direccion", "Email", "Telefono"
            }
        ));
        tblProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProveedorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProveedor);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 748, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblProveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProveedorMouseClicked
        int fila = this.tblProveedor.rowAtPoint(evt.getPoint());
        
        GenerarCompraInter.txtCodigoProveedor.setText(this.modeloProveedor.getValueAt(fila, 0).toString());
        GenerarCompraInter.lblNombreProveedor.setText(this.modeloProveedor.getValueAt(fila, 2).toString());
        this.dispose();
    }//GEN-LAST:event_tblProveedorMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblProveedor;
    // End of variables declaration//GEN-END:variables

    private void refrescarVentana() {
        this.modeloProveedor.setRowCount(0);
        cargarTabla();
    }

    private void cargarTabla() {
        Iterator<Proveedor> itProveedor = this.miControladoraVisual.traerProveedor().iterator();
        Proveedor unProveedor;
        while (itProveedor.hasNext()) {
            unProveedor = itProveedor.next();
            this.modeloProveedor.addRow(new Object[]{unProveedor.getCodigo(), unProveedor.getCuit(), unProveedor.getNombre(), unProveedor.getDireccion(), unProveedor.getEmail(), unProveedor.getTelefono()});
        }
    }
}
