/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visual;

import Logica.Articulo;
import java.util.Iterator;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pepex3
 */
public class BusquedaArticuloCompraInter extends javax.swing.JInternalFrame {

    private ControladoraVisual miControladoraVisual;
    private DefaultTableModel modeloArticulo;
    /**
     * Creates new form BusquedaArticuloCompraInter
     */
    public BusquedaArticuloCompraInter(ControladoraVisual miControladoraVisual) {
        initComponents();
        this.miControladoraVisual=miControladoraVisual;
        this.modeloArticulo=(DefaultTableModel)this.tblArticulo.getModel();
        refrescarVentana();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblArticulo = new javax.swing.JTable();

        setClosable(true);
        setResizable(true);
        setTitle("Articulos");

        tblArticulo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Cantidad", "Precio"
            }
        ));
        tblArticulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblArticuloMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblArticulo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblArticuloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblArticuloMouseClicked
       int fila = this.tblArticulo.rowAtPoint(evt.getPoint());
       
       GenerarCompraInter.lblCodigoArticulo.setText(this.modeloArticulo.getValueAt(fila, 0).toString());
       GenerarCompraInter.lblNombreArticulo.setText(this.modeloArticulo.getValueAt(fila, 1).toString());
       GenerarCompraInter.lblPrecioArticulo.setText(this.modeloArticulo.getValueAt(fila, 3).toString());
       this.dispose();
    }//GEN-LAST:event_tblArticuloMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblArticulo;
    // End of variables declaration//GEN-END:variables

    private void refrescarVentana() {
        this.modeloArticulo.setRowCount(0);
        cargarTabla();
    }

    private void cargarTabla() {
        Iterator<Articulo> itArticulo = this.miControladoraVisual.traerArticulo().iterator();
        Articulo unArticulo;
        while (itArticulo.hasNext()) {
            unArticulo = itArticulo.next();
            this.modeloArticulo.addRow(new Object[]{unArticulo.getCodigo(),unArticulo.getNombre(),unArticulo.getCantidad(),unArticulo.getPrecio()});
        }
    }
}
