/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visual;

import Logica.Cliente;
import java.util.Iterator;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pepe
 */
public class ClienteBusquedaInter extends javax.swing.JInternalFrame {

    private ControladoraVisual miControladoraVisual;
    private DefaultTableModel modeloClienteBusqueda;
    /**
     * Creates new form ClienteBusquedaInter
     */
    public ClienteBusquedaInter(ControladoraVisual miControladoraVisual) {
        initComponents();
        this.miControladoraVisual=miControladoraVisual;
        this.modeloClienteBusqueda=(DefaultTableModel) this.tblCliente.getModel();
        refrescarVentana();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCliente = new javax.swing.JTable();

        setClosable(true);
        setResizable(true);
        setTitle("Clientes");

        tblCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Dni", "Cuil", "Nombre", "Apellido", "Direccioin", "Email", "Telefono"
            }
        ));
        tblCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCliente);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClienteMouseClicked
       GenerarVentaArticuloInter.txtCodigoCliente.setText(null);
       GenerarVentaArticuloInter.lblNombreCliente.setText(null);
       
       int fila = this.tblCliente.rowAtPoint(evt.getPoint());
       
       GenerarVentaArticuloInter.txtCodigoCliente.setText(this.modeloClienteBusqueda.getValueAt(fila, 0).toString());
       GenerarVentaArticuloInter.lblNombreCliente.setText(this.modeloClienteBusqueda.getValueAt(fila, 3).toString() + " " +this.modeloClienteBusqueda.getValueAt(fila, 4).toString());
       this.dispose();
    }//GEN-LAST:event_tblClienteMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCliente;
    // End of variables declaration//GEN-END:variables

    private void refrescarVentana() {
        this.modeloClienteBusqueda.setRowCount(0);
        cargarTablaCliente();
    }

    private void cargarTablaCliente() {
        Iterator <Cliente> itCliente = this.miControladoraVisual.traerCliente().iterator();
        Cliente unCliente;
        while(itCliente.hasNext())
        {
            unCliente=itCliente.next();
            modeloClienteBusqueda.addRow(new Object[]{unCliente.getCodigo(),unCliente.getDni(),unCliente.getCuil(),unCliente.getNombre(),unCliente.getApellido(),unCliente.getDireccion(),unCliente.getEmail(),unCliente.getTelefono()});
        }
    }
}
