/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visual;

import Logica.Articulo;
import Logica.Consumible;
import Logica.Detalle;
import Logica.DetalleCompraVenta;
import Logica.Encabezado;
import Logica.Proveedor;
import Logica.TipoCompra;
import Logica.TipoComprobante;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Facu
 */
public class GenerarCompraInter extends javax.swing.JInternalFrame {

    private ControladoraVisual miControladoraVisual;
    private DefaultTableModel modeloDetalle;
    private int fila;
    private int codigoDetalle;

    public GenerarCompraInter(ControladoraVisual miControladoraVisual) {
        initComponents();
        GenerarCompraInter.txtCodigoProveedor.setVisible(false);
        this.miControladoraVisual = miControladoraVisual;
        this.modeloDetalle = (DefaultTableModel) this.tblDetallesCompraVenta.getModel();
        this.cmdAgregarArticulo.setEnabled(false);
        this.cmdGenerarCompra.setEnabled(false);
        refrescarVentana();
        cargarCmbCompra();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cldFecha = new com.toedter.calendar.JDateChooser();
        txtCodigoProveedor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblNombreProveedor = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbComprobanteCompra = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        lblCodigoArticulo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblNombreArticulo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblPrecioArticulo = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCantidadArticulo = new javax.swing.JTextField();
        cmdBuscarArticulo = new javax.swing.JButton();
        cmdAgregarArticulo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDetallesCompraVenta = new javax.swing.JTable();
        cmdBorrarRenglon = new javax.swing.JButton();
        cmdCrearArticulo = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        cmdGenerarCompra = new javax.swing.JButton();
        cmdVerCompras = new javax.swing.JButton();
        cmdBuscarProveedor = new javax.swing.JButton();

        setClosable(true);
        setTitle("Compra");

        jLabel1.setText("Nombre Proveedor:");

        lblNombreProveedor.setText("Proveedor");

        jLabel2.setText("Comprobante:");

        cmbComprobanteCompra.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Codigo Articulo:");

        lblCodigoArticulo.setText("xxxxxx");

        jLabel4.setText("Nombre Articulo:");

        lblNombreArticulo.setText("Articulo");

        jLabel5.setText("Precio:");

        jLabel6.setText("$");

        lblPrecioArticulo.setText("0.00");

        jLabel7.setText("Cantidad:");

        cmdBuscarArticulo.setText("Buscar Articulo");
        cmdBuscarArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBuscarArticuloActionPerformed(evt);
            }
        });

        cmdAgregarArticulo.setText("Agregar Articulo");
        cmdAgregarArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAgregarArticuloActionPerformed(evt);
            }
        });

        tblDetallesCompraVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Articulo", "Cantidad", "Subtotal"
            }
        ));
        tblDetallesCompraVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDetallesCompraVentaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDetallesCompraVenta);

        cmdBorrarRenglon.setText("Borrar Renglon");
        cmdBorrarRenglon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBorrarRenglonActionPerformed(evt);
            }
        });

        cmdCrearArticulo.setText("Crear Articulo");
        cmdCrearArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCrearArticuloActionPerformed(evt);
            }
        });

        jLabel8.setText("Total:");

        jLabel9.setText("$");

        lblTotal.setText("0.00");

        cmdGenerarCompra.setText("Generar Compra");
        cmdGenerarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdGenerarCompraActionPerformed(evt);
            }
        });

        cmdVerCompras.setText("Ver Compras");
        cmdVerCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdVerComprasActionPerformed(evt);
            }
        });

        cmdBuscarProveedor.setText("Buscar Proveedor");
        cmdBuscarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBuscarProveedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNombreProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblCodigoArticulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblNombreArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblPrecioArticulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(cmbComprobanteCompra, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtCantidadArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(44, 44, 44))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(128, 128, 128)
                                .addComponent(txtCodigoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cldFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmdAgregarArticulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmdBuscarArticulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmdBuscarProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cmdCrearArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmdVerCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmdBorrarRenglon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmdGenerarCompra, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))))))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCodigoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cldFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblNombreProveedor)
                    .addComponent(jLabel2)
                    .addComponent(cmbComprobanteCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdBuscarProveedor))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblCodigoArticulo)
                    .addComponent(jLabel7)
                    .addComponent(txtCantidadArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdBuscarArticulo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblNombreArticulo)
                    .addComponent(jLabel5)
                    .addComponent(lblPrecioArticulo)
                    .addComponent(cmdAgregarArticulo)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdBorrarRenglon)
                    .addComponent(cmdCrearArticulo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(jLabel9)
                        .addComponent(lblTotal)
                        .addComponent(cmdGenerarCompra))
                    .addComponent(cmdVerCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdBuscarArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBuscarArticuloActionPerformed
        BusquedaArticuloCompraInter unArticuloCompraInter = new BusquedaArticuloCompraInter(miControladoraVisual);
        MenuPrincipal.Escritorio.add(unArticuloCompraInter);
        unArticuloCompraInter.show();
        this.cmdAgregarArticulo.setEnabled(true);
    }//GEN-LAST:event_cmdBuscarArticuloActionPerformed

    private void cmdBuscarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBuscarProveedorActionPerformed
        BusquedaProveedorInter unBusquedaProveedorInter = new BusquedaProveedorInter(miControladoraVisual);
        MenuPrincipal.Escritorio.add(unBusquedaProveedorInter);
        unBusquedaProveedorInter.show();
    }//GEN-LAST:event_cmdBuscarProveedorActionPerformed

    private void cmdAgregarArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAgregarArticuloActionPerformed
        Consumible unConsumible = (Consumible) this.miControladoraVisual.buscarArticulo(Integer.parseInt(GenerarCompraInter.lblCodigoArticulo.getText()));
        Double subtotal = Integer.parseInt(txtCantidadArticulo.getText()) * Double.parseDouble(lblPrecioArticulo.getText());
        Double total = subtotal + Double.parseDouble(this.lblTotal.getText());
        try {
            int codigoDetalle = this.miControladoraVisual.generarDetalleCompraVenta(Integer.parseInt(txtCantidadArticulo.getText()), unConsumible, subtotal);
            this.miControladoraVisual.sumarArticulo(Integer.parseInt(txtCantidadArticulo.getText()), Integer.parseInt(this.lblCodigoArticulo.getText()));
            this.lblTotal.setText(String.valueOf(total));
            refrescarVentanaArticulo();
            cargarTablaDetalle(codigoDetalle);
        } catch (Exception ex) {
            Logger.getLogger(GenerarCompraInter.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmdAgregarArticuloActionPerformed

    private void cmdGenerarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdGenerarCompraActionPerformed
        List<Detalle> unosDetalles = new LinkedList();
        Calendar fecha= new GregorianCalendar();
        DetalleCompraVenta unDetalleCompraVenta;
        Encabezado unEncabezado;
        TipoComprobante unTipoComprobante;
        Proveedor unProveedor;
        int codigo;
        int codigoComp;
        int codigoEncab;
        Double total = 0.00;
        String cadena = (String) this.cmbComprobanteCompra.getSelectedItem();
        String[] partes = cadena.split("-");
        codigoComp = Integer.parseInt(partes[0]);
        for (int i = 0; i < modeloDetalle.getRowCount(); i++) {
            codigo = Integer.parseInt(this.modeloDetalle.getValueAt(i, 0).toString());
            unDetalleCompraVenta = this.miControladoraVisual.buscarDetalleCompraVenta(codigo);
            total = total + unDetalleCompraVenta.getSubtotal();
            unosDetalles.add(unDetalleCompraVenta);
        }
        unTipoComprobante = this.miControladoraVisual.buscarTipoCompra(codigoComp);
        fecha=this.cldFecha.getCalendar();
        unProveedor=this.miControladoraVisual.buscarProveedor(Integer.parseInt(txtCodigoProveedor.getText()));
        try {
            codigoEncab=this.miControladoraVisual.generarEncabezado(fecha, unProveedor, unTipoComprobante, unosDetalles, total);
            unEncabezado=this.miControladoraVisual.buscarEncabezado(codigoEncab);
            this.miControladoraVisual.agregarCompra(unEncabezado);
            refrescarVentana();
        } catch (Exception ex) {
            Logger.getLogger(GenerarCompraInter.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmdGenerarCompraActionPerformed

    private void cmdCrearArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCrearArticuloActionPerformed
        AltaArticuloInter unAltaArticuloInter = new AltaArticuloInter(miControladoraVisual);
        MenuPrincipal.Escritorio.add(unAltaArticuloInter);
        unAltaArticuloInter.show();
    }//GEN-LAST:event_cmdCrearArticuloActionPerformed

    private void cmdBorrarRenglonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBorrarRenglonActionPerformed
         try {
            DetalleCompraVenta unDetalle = this.miControladoraVisual.buscarDetalleCompraVenta(this.codigoDetalle);
            int codigoArticulo = unDetalle.getUnConsumible().getCodigo();
            this.miControladoraVisual.descontarArticulo(unDetalle.getCantidad(), codigoArticulo);
            this.miControladoraVisual.borrarDetalleCompraVenta(unDetalle.getCodigo());
            this.modeloDetalle.removeRow(this.fila);
            this.lblTotal.setText(String.valueOf(Double.parseDouble(lblTotal.getText()) - unDetalle.getSubtotal()));
        } catch (Exception ex) {
            Logger.getLogger(GenerarVentaArticuloInter.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmdBorrarRenglonActionPerformed

    private void cmdVerComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdVerComprasActionPerformed
        ListarCompraInter unListarCompraInter = new ListarCompraInter(miControladoraVisual);
        MenuPrincipal.Escritorio.add(unListarCompraInter);
        unListarCompraInter.show();
    }//GEN-LAST:event_cmdVerComprasActionPerformed

    private void tblDetallesCompraVentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDetallesCompraVentaMouseClicked
        this.fila = this.tblDetallesCompraVenta.rowAtPoint(evt.getPoint());
        this.codigoDetalle = Integer.parseInt(this.modeloDetalle.getValueAt(fila, 0).toString());
    }//GEN-LAST:event_tblDetallesCompraVentaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser cldFecha;
    private javax.swing.JComboBox<String> cmbComprobanteCompra;
    private javax.swing.JButton cmdAgregarArticulo;
    private javax.swing.JButton cmdBorrarRenglon;
    private javax.swing.JButton cmdBuscarArticulo;
    private javax.swing.JButton cmdBuscarProveedor;
    private javax.swing.JButton cmdCrearArticulo;
    private javax.swing.JButton cmdGenerarCompra;
    private javax.swing.JButton cmdVerCompras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JLabel lblCodigoArticulo;
    public static javax.swing.JLabel lblNombreArticulo;
    public static javax.swing.JLabel lblNombreProveedor;
    public static javax.swing.JLabel lblPrecioArticulo;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tblDetallesCompraVenta;
    private javax.swing.JTextField txtCantidadArticulo;
    public static javax.swing.JTextField txtCodigoProveedor;
    // End of variables declaration//GEN-END:variables

    private void refrescarVentana() {
        GenerarCompraInter.txtCodigoProveedor.setText(null);
        GenerarCompraInter.lblNombreProveedor.setText("Proveedor");
        GenerarCompraInter.lblCodigoArticulo.setText("xxxxxx");
        GenerarCompraInter.lblNombreArticulo.setText("Articulo");
        GenerarCompraInter.lblPrecioArticulo.setText("0.00");
        this.cmbComprobanteCompra.removeAllItems();
        this.modeloDetalle.setRowCount(0);
        this.lblTotal.setText("0.00");
        this.txtCantidadArticulo.setText(null);
    }

    private void cargarCmbCompra() {
        Iterator<TipoCompra> itCompra = this.miControladoraVisual.traerTipoCompra().iterator();
        TipoCompra unTipoCompra;
        while (itCompra.hasNext()) {
            unTipoCompra = itCompra.next();
            this.cmbComprobanteCompra.addItem(unTipoCompra.toString());
        }
    }

    private void refrescarVentanaArticulo() {
        GenerarCompraInter.lblCodigoArticulo.setText("xxxxxx");
        GenerarCompraInter.lblNombreArticulo.setText("Articulo");
        GenerarCompraInter.lblPrecioArticulo.setText("0.00");
        this.txtCantidadArticulo.setText(null);
    }

    private void cargarTablaDetalle(int codigoDetalle) {
        DetalleCompraVenta unDetalleCompraVenta = this.miControladoraVisual.buscarDetalleCompraVenta(codigoDetalle);
        Articulo unArticulo = (Articulo) unDetalleCompraVenta.getUnConsumible();
        this.modeloDetalle.addRow(new Object[]{unDetalleCompraVenta.getCodigo(), unArticulo.getNombre(), unDetalleCompraVenta.getCantidad(), unDetalleCompraVenta.getSubtotal()});
        this.cmdGenerarCompra.setEnabled(true);
    }
}
