/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visual;

import Logica.DetalleCompraVenta;
import Logica.Tecnico;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pepe
 */
public class ListarServicioTecnicoInter extends javax.swing.JInternalFrame {

    private ControladoraVisual miControladoraVisual;
    private DefaultTableModel modeloTecnico;
    private DefaultTableModel modeloDetalle;
    private int fila;

    /**
     * Creates new form ListarServicioTecnicoInter
     */
    public ListarServicioTecnicoInter(ControladoraVisual miControladoraVisual) {
        initComponents();
        this.miControladoraVisual = miControladoraVisual;
        this.modeloDetalle = (DefaultTableModel) this.tblDetalleCompraVenta.getModel();
        this.modeloTecnico = (DefaultTableModel) this.tblServicioTecnico.getModel();
        this.tblDetalleCompraVenta.setEnabled(false);
        refrescarVentana();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblServicioTecnico = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDetalleCompraVenta = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        cmBorrar = new javax.swing.JButton();

        setClosable(true);
        setResizable(true);
        setTitle("Servicio Tecnico");

        tblServicioTecnico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Codigo", "Descripcion", "Subtotal"
            }
        ));
        tblServicioTecnico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblServicioTecnicoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblServicioTecnico);

        tblDetalleCompraVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Cantidad", "Articulo", "Subtotal"
            }
        ));
        jScrollPane2.setViewportView(tblDetalleCompraVenta);

        jLabel1.setText("Detalles:");

        cmBorrar.setText("Borrar Servicio");
        cmBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmBorrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)
                            .addComponent(jScrollPane2))
                        .addComponent(jLabel1))
                    .addComponent(cmBorrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cmBorrar)
                .addGap(86, 86, 86))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblServicioTecnicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblServicioTecnicoMouseClicked
       int codigo;
       Tecnico unTecnico;
       List<DetalleCompraVenta> unosDetalleCompraVenta=new LinkedList<>();
       modeloDetalle.setRowCount(0);
       
       this.fila = this.tblServicioTecnico.rowAtPoint(evt.getPoint());
       
       codigo = Integer.parseInt(this.modeloTecnico.getValueAt(this.fila, 0).toString());
       unTecnico=this.miControladoraVisual.buscarServicioTecnico(codigo);
       unosDetalleCompraVenta=unTecnico.getUnosDetalleCompraVentas();
       
       Iterator<DetalleCompraVenta> itDetalle = unosDetalleCompraVenta.iterator();
       DetalleCompraVenta unDetalle;
       while(itDetalle.hasNext()){
           unDetalle=itDetalle.next();
           modeloDetalle.addRow(new Object[]{unDetalle.getCodigo(),unDetalle.getCantidad(),unDetalle.getUnConsumible().getDescripcion(),unDetalle.getSubtotal()});
       }
    }//GEN-LAST:event_tblServicioTecnicoMouseClicked

    private void cmBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmBorrarActionPerformed
       int codigo=Integer.parseInt(this.modeloTecnico.getValueAt(this.fila, 0).toString());
        try {
            this.miControladoraVisual.borrarServicioTecnico(codigo);
            refrescarVentana();
        } catch (Exception ex) {
            Logger.getLogger(ListarServicioTecnicoInter.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_cmBorrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmBorrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblDetalleCompraVenta;
    private javax.swing.JTable tblServicioTecnico;
    // End of variables declaration//GEN-END:variables

    private void refrescarVentana() {
        this.modeloDetalle.setRowCount(0);
        this.modeloTecnico.setRowCount(0);
        cargarTablaServicio();
    }

    private void cargarTablaServicio() {
        Iterator<Tecnico> itTecnico = this.miControladoraVisual.traerServicioTecnico().iterator();
        Tecnico unTecnico;
        while (itTecnico.hasNext()) {
            unTecnico = itTecnico.next();
            modeloTecnico.addRow(new Object[]{unTecnico.getCodigo(),unTecnico.getDescripcion(),unTecnico.getSubtotal()});
        }
    }
}
