/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visual;

import Logica.Tecnologia;
import java.util.Iterator;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pepex3
 */
public class ListarTecnologiaInter extends javax.swing.JInternalFrame {

    private ControladoraVisual miControladoraVisual;
    private DefaultTableModel modeloTecnologia;
    /**
     * Creates new form ListarTecnologiaInter
     */
    public ListarTecnologiaInter(ControladoraVisual miControladoraVisual) {
        initComponents();
        this.miControladoraVisual=miControladoraVisual;
        this.modeloTecnologia=(DefaultTableModel)this.tblTecnologia.getModel();
        refrescarVentana();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblTecnologia = new javax.swing.JTable();

        setClosable(true);
        setResizable(true);
        setTitle("Tecnologias");

        tblTecnologia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Codigo", "Descripcion", "Tipo de Tecnologia"
            }
        ));
        tblTecnologia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTecnologiaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTecnologia);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 725, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblTecnologiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTecnologiaMouseClicked
        int fila=this.tblTecnologia.rowAtPoint(evt.getPoint());
        
        AltaProyectoInter.modeloTecnologiaProyec.addRow(new Object[]{this.modeloTecnologia.getValueAt(fila, 0).toString(),this.modeloTecnologia.getValueAt(fila, 1).toString(),this.modeloTecnologia.getValueAt(fila, 2).toString()});
        this.dispose();
    }//GEN-LAST:event_tblTecnologiaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTecnologia;
    // End of variables declaration//GEN-END:variables

    private void refrescarVentana() {
        this.modeloTecnologia.setRowCount(0);
        cargarTabla();
    }

    private void cargarTabla() {
        Iterator<Tecnologia> itConcepto= this.miControladoraVisual.traerTecnologias().iterator();
        Tecnologia unTecnologia;
        while(itConcepto.hasNext()){
            unTecnologia=itConcepto.next();
            this.modeloTecnologia.addRow(new Object[]{unTecnologia.getCodigo(),unTecnologia.getDescripcion(),unTecnologia.getUnTipoTecnologia().getDescripcion()});
        }
    }
}
