/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visual;



/**
 *
 * @author Facu
 */
public class MenuPrincipal extends javax.swing.JFrame {

    //Controladora Visual
    private ControladoraVisual miControladoraVisual;

    //Relaciones
//        private AgregarOrdenDeTrabajo unAgregarOrdenDeTrabajo = new AgregarOrdenDeTrabajo();
//        private AgregarServicioOrden unAgregarServicioOrden = new AgregarServicioOrden();
//        private AltaActividadAdministrativa unAltaActividadAdministrativa = new AltaActividadAdministrativa();
//        private AltaActividadProyecto unAltaActividadProyecto = new AltaActividadProyecto();
//        private AltaActividadTecnica unAltaActividadTecnica = new AltaActividadTecnica();
//        private AltaArticulo unAltaArticulo = new AltaArticulo();
//
//        private AltaEmpleado unAltaEmpleado = new AltaEmpleado();
//        private AltaEquipo unAltaEquipo = new AltaEquipo();
//        private AltaProveedor unAltaProveedor = new AltaProveedor();
//        private AltaProyecto unAltaProyecto = new AltaProyecto();
//        private AltaTecnologia unAltaTecnologia = new AltaTecnologia();
//        private AltaTipoTecnologia unAltaTipoTecnologia = new AltaTipoTecnologia();
//        private AltaTipoCompra unAltaTipoCompra = new AltaTipoCompra();
//        private AltaTipoEstado unAltaTipoEstado = new AltaTipoEstado();
//        private AltaTipoLiquidacion unAltaTipoLiquidacion = new AltaTipoLiquidacion();
//        private AltaTipoVençççta unAltaTipoVenta = new AltaTipoVenta();
//        private AsignarEmpleadoProyecto unAsignarEmpleadoProyecto = new AsignarEmpleadoProyecto();
//        private AsignarEmpleadoServicio unAsignarEmpleadoServicio = new AsignarEmpleadoServicio();
//        private GenerarCompra unGenerarCompra = new GenerarCompra();
//        private GenerarIngresoEquipo unGenerarIngresoEquipo = new GenerarIngresoEquipo();
//        private GenerarSalidaEquipo unGenerarSalidaEquipo = new GenerarSalidaEquipo();
//        private GenerarOrden unGenerarOrden = new GenerarOrden();
//        private GenerarLiquidacion unGenerarLiquidacion = new GenerarLiquidacion();
//        private VentaArticulo unVentaArticulo = new VentaArticulo();
//        private VentaServicio unVentaServicio = new VentaServicio();
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal(ControladoraVisual miControladoraVisual) 
    {
        this.miControladoraVisual = miControladoraVisual;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        Escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mitActividadAdministrativa = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        mnuActAdministrativa = new javax.swing.JMenuItem();
        mnuActProyecto = new javax.swing.JMenuItem();
        mnuActTecnica = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setResizable(true);
        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1020, Short.MAX_VALUE)
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 527, Short.MAX_VALUE)
        );

        jMenu1.setText("File");

        mitActividadAdministrativa.setText("Actividad Administrativa");
        mitActividadAdministrativa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitActividadAdministrativaActionPerformed(evt);
            }
        });
        jMenu1.add(mitActividadAdministrativa);

        jMenuItem1.setText("Cliente");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Tipo de Tecnologia");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Tecnologia");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Altas");

        jMenu4.setText("Actividades");

        mnuActAdministrativa.setText("Administrativa");
        mnuActAdministrativa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuActAdministrativaActionPerformed(evt);
            }
        });
        jMenu4.add(mnuActAdministrativa);

        mnuActProyecto.setText("Proyecto");
        mnuActProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuActProyectoActionPerformed(evt);
            }
        });
        jMenu4.add(mnuActProyecto);

        mnuActTecnica.setText("Tecnica");
        mnuActTecnica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuActTecnicaActionPerformed(evt);
            }
        });
        jMenu4.add(mnuActTecnica);

        jMenu3.add(jMenu4);

        jMenuItem4.setText("jMenuItem4");
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        jInternalFrame1.setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addComponent(Escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mitActividadAdministrativaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitActividadAdministrativaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mitActividadAdministrativaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        AltaClienteInter unAltaCliente = new AltaClienteInter();
        this.Escritorio.add(unAltaCliente);
        unAltaCliente.show();
        
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        AltaTipoTecnologiaInter unAlta = new AltaTipoTecnologiaInter(this.miControladoraVisual);
        this.Escritorio.add(unAlta);
        unAlta.show();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        AltaTecnologiaInter unAlta = new AltaTecnologiaInter(this.miControladoraVisual);
        this.Escritorio.add(unAlta);
        unAlta.show();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void mnuActAdministrativaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuActAdministrativaActionPerformed
        AltaActividadAdministrativaInter AltaActAdmin = new AltaActividadAdministrativaInter();
        this.Escritorio.add(AltaActAdmin);
        AltaActAdmin.show();
    }//GEN-LAST:event_mnuActAdministrativaActionPerformed

    private void mnuActProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuActProyectoActionPerformed
        AltaActividadProyectoInter AltaActProyec = new AltaActividadProyectoInter();
        this.Escritorio.add(AltaActProyec);
        AltaActProyec.show();
    }//GEN-LAST:event_mnuActProyectoActionPerformed

    private void mnuActTecnicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuActTecnicaActionPerformed
        AltaActividadTecnicaInter AltaActTec = new AltaActividadTecnicaInter();
        this.Escritorio.add(AltaActTec);
        AltaActTec.show();
    }//GEN-LAST:event_mnuActTecnicaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem mitActividadAdministrativa;
    private javax.swing.JMenuItem mnuActAdministrativa;
    private javax.swing.JMenuItem mnuActProyecto;
    private javax.swing.JMenuItem mnuActTecnica;
    // End of variables declaration//GEN-END:variables

    
}
